### ISSUE TITLE
Do you have a model ?

### ISSUE THREAD

**Issue by ebanDev** [parolrekonado/deepspeech-esperanto#1]
Hi ! Do you have a model for deepspeech in esperanto ? :)

**Comment by 54696d21** [comment]
currently not

**Comment by ebanDev** [comment]
Oh ok :/

**Comment by stefangrotz** [comment]
@bidaian I started to train a model with the 720 hours of the latest release, you can find it in the deepspeech-coqui folder. I will add better ones once I have them, right now I have a word error rate of around 25%. I also will update the documentation in the readme in the next months.
